version: '3.9'
services:
  mail:
    image: mailhog/mailhog
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
  web:
    image: myshoppress/devimage
    #dockerentry point custom command. type docker run --rm -it myshoppress/devimage usage to see available options
    command: ["start"]
    ports:
      - "8080:80"
    working_dir: ${WORKING_DIR:-/usr/src/app}
    environment:
      DOCKER_INIT_SCRIPT: ${WORKING_DIR:-/usr/src/app}/scripts/docker-init.sh
      DOCKER_INIT_SKIP: 0 #if set to 1 the above screen will not execute
      WP_ROOT: ${WP_ROOT:-/srv/app} #where the wp be installed
      WP_ENV: 'development'
      WP_VERSION: 5.3.3
      SMTP_HOST: mailhog #uses the mailhog but can be changed to use any mailtrap service
      SMTP_PORT: 1025
      DB_URL: "mysql://root:root@db/dev_db"
      HTTP_HOST: app.localhost
      WP_ADMIN_USER: root   #create an wp admin create
      WP_ADMIN_PASS: root
    depends_on:
      - db
    volumes:
      - .:${WORKING_DIR:-/usr/src/app}